"use client";
import { useState } from 'react';
import { Plus, MoreVertical, Calendar, User, Zap, Brain, ArrowDownCircle, ArrowUpCircle } from 'lucide-react';
import styles from './tasks.module.css';
import toast from 'react-hot-toast';

export default function TasksPage() {
    // Initial mockup tasks for prototype mode
    const [tasks, setTasks] = useState({
        todo: [
            { id: 1, title: 'Review Q3 Financial Modeling', desc: 'Generated by AI from Q3_Financial_Review.pdf analyze insights.', priority: 'High', due: '2h' },
            { id: 2, title: 'Update Security Compliance', desc: 'Routine check for ISO compliance standards across active microservices.', priority: 'Low', due: 'Tomorrow' }
        ] as any[],
        inProgress: [
            { id: 3, title: 'Draft Marketing Campaign Brief', desc: 'Collaborating with design team for assets generation.', priority: 'Active', due: 'Today' }
        ] as any[],
        completed: [
            { id: 4, title: 'Vendor Onboarding Process', completedAt: '2 hours ago' }
        ] as any[]
    });

    const handleCreateTask = () => {
        console.log("Button clicked: Add Task");
        const taskName = window.prompt("Enter task name:", "New Workflow Task");

        if (!taskName) {
            toast('Task creation cancelled', { icon: '✖️', id: 'cancel_task' });
            return;
        }

        toast.success(`Task "${taskName}" created successfully`, { id: 'create_task' });

        const newTask = { id: Date.now(), title: taskName, desc: 'Manually added workflow task.', priority: 'Normal', due: 'TBD' };

        setTasks(prev => ({
            ...prev,
            todo: [newTask, ...prev.todo]
        }));
    };

    const handleMoveTask = (taskId: number, currentColumn: 'todo' | 'inProgress', targetColumn: 'inProgress' | 'completed') => {
        console.log("Card action: Double-clicked task to move", { taskId, currentColumn, targetColumn });

        let movedItem: any;
        const newCurrent = tasks[currentColumn].filter(t => {
            if (t.id === taskId) { movedItem = t; return false; }
            return true;
        });

        if (movedItem) {
            setTasks(prev => ({
                ...prev,
                [currentColumn]: newCurrent,
                [targetColumn]: [movedItem, ...prev[targetColumn]]
            }));
            toast.success('Task status updated', { id: 'move_task' });
        }
    };

    const handleApplySuggestion = (suggestionDesc: string) => {
        console.log("Button clicked: Apply Suggestion", { suggestionDesc });
        toast.success('Workflow priority rebalanced.', { id: 'opt' });
    };

    const handleDismissSuggestion = () => {
        console.log("Button clicked: Dismiss Suggestion");
        toast('Suggestion dismissed', { icon: '✖️' });
    };

    return (
        <div className={styles.container}>
            <header className={styles.header}>
                <div>
                    <h1 className={styles.title}>Workflow Engine</h1>
                    <p className={styles.subtitle}>AI-Optimized Task Orchestration</p>
                </div>
                <button className="btn-primary" onClick={handleCreateTask}>
                    <Plus size={18} /> Add Task
                </button>
            </header>

            <div className={styles.mainLayout}>
                {/* Kanban Board */}
                <div className={styles.kanbanArea}>
                    {/* To Do Column */}
                    <div className={styles.kanbanColumn}>
                        <div className={styles.columnHeader}>
                            <div className={styles.columnTitle}>
                                <span className={styles.dot} style={{ background: 'var(--text-muted)' }}></span>
                                To Do
                                <span className={styles.taskCount}>{tasks.todo.length}</span>
                            </div>
                            <button className={styles.iconBtn} onClick={() => console.log('Button clicked: Refresh column')}><MoreVertical size={16} /></button>
                        </div>
                        <div className={styles.taskList}>
                            {tasks.todo.length === 0 && <p className="text-muted text-sm text-center">No tasks</p>}
                            {tasks.todo.map(task => (
                                <div key={task.id} className={`glass-panel ${styles.taskCard}`} onDoubleClick={() => handleMoveTask(task.id, 'todo', 'inProgress')}>
                                    <div className={styles.taskPriority}>
                                        {task.priority === 'High' ? <ArrowUpCircle size={14} className="accent-text" /> : <ArrowDownCircle size={14} color="#a3a3a3" />}
                                        {task.priority || 'Normal'}
                                    </div>
                                    <h4 className={styles.taskTitle}>{task.title}</h4>
                                    <p className={styles.taskDesc}>{task.desc}</p>
                                    <div className={styles.taskFooter}>
                                        <div className={styles.taskMeta}><Calendar size={14} /> {task.due || 'N/A'}</div>
                                        <div className={styles.taskAssignee}><User size={14} /></div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* In Progress Column */}
                    <div className={styles.kanbanColumn}>
                        <div className={styles.columnHeader}>
                            <div className={styles.columnTitle}>
                                <span className={styles.dot} style={{ background: '#3b82f6' }}></span>
                                In Progress
                                <span className={styles.taskCount}>{tasks.inProgress.length}</span>
                            </div>
                            <button className={styles.iconBtn}><MoreVertical size={16} /></button>
                        </div>
                        <div className={styles.taskList}>
                            {tasks.inProgress.map(task => (
                                <div key={task.id} className={`glass-panel ${styles.taskCard} ${styles.taskActive}`} onDoubleClick={() => handleMoveTask(task.id, 'inProgress', 'completed')}>
                                    <div className={styles.taskPriority}><Zap size={14} className="accent-text" /> Active</div>
                                    <h4 className={styles.taskTitle}>{task.title}</h4>
                                    <p className={styles.taskDesc}>{task.desc}</p>
                                    <div className={styles.progressBar}><div className={styles.progressFill} style={{ width: '60%' }}></div></div>
                                    <div className={styles.taskFooter}>
                                        <div className={styles.taskMeta}><Calendar size={14} /> {task.due || 'N/A'}</div>
                                        <div className={styles.taskAssignee}>JD</div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Completed Column */}
                    <div className={styles.kanbanColumn}>
                        <div className={styles.columnHeader}>
                            <div className={styles.columnTitle}>
                                <span className={styles.dot} style={{ background: '#22c55e' }}></span>
                                Completed
                                <span className={styles.taskCount}>{tasks.completed.length}</span>
                            </div>
                            <button className={styles.iconBtn}><MoreVertical size={16} /></button>
                        </div>
                        <div className={styles.taskList}>
                            {tasks.completed.map(task => (
                                <div key={task.id} className={`glass-panel ${styles.taskCard} ${styles.taskCompleted}`}>
                                    <h4 className={styles.taskTitle}>{task.title}</h4>
                                    <div className={styles.taskFooter}>
                                        <div className={styles.taskMeta}>{task.completedAt || 'Recently'}</div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>

                {/* AI Side Panel */}
                <div className={styles.aiPanel}>
                    <div className={styles.panelHeader}>
                        <Brain size={20} className="accent-text" />
                        <h3>Optimization Engine</h3>
                    </div>

                    <div className={styles.panelSection}>
                        <h4 className={styles.sectionTitle}>Smart Priority Suggestions</h4>
                        <div className={styles.suggestionCard}>
                            <p className={styles.suggestionText}>
                                Move <strong>"Review Q3 Financial Modeling"</strong> to today. It blocks the CFO&apos;s weekly review.
                            </p>
                            <div className={styles.suggestionActions}>
                                <button className={styles.acceptBtn} onClick={() => handleApplySuggestion('Move Q3 Modeling to today')}>Apply</button>
                                <button className={styles.rejectBtn} onClick={handleDismissSuggestion}>Dismiss</button>
                            </div>
                        </div>
                    </div>

                    <div className={styles.panelSection}>
                        <h4 className={styles.sectionTitle}>Workflow Bottlenecks</h4>
                        <div className={styles.warningCard}>
                            <Zap size={16} className="accent-text" />
                            <p>Design team is overloaded. 3 tasks in Review phase are delayed.</p>
                        </div>
                    </div>

                    <div className={styles.panelSection}>
                        <h4 className={styles.sectionTitle}>Auto-Delegate</h4>
                        <div className={styles.delegateCard}>
                            <p>AI can draft the compliance report and assign it for your review.</p>
                            <button className={styles.acceptBtn} style={{ width: '100%', marginTop: '0.5rem' }} onClick={() => handleApplySuggestion('Draft compliance report')}>Execute Autobot</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
